export const templateList = [
    {
        name: '空白',
        size: '尺寸自定',
        description: '在空白的画布上尽情施展您的创意吧！',
        isdeleted: 0,
        priority: 1, 
        level: 1,
        thumbnail: 'https://datav.oss-cn-hangzhou.aliyuncs.com/uploads/templates/7.png',
        snapshot: 'https://datav.oss-cn-hangzhou.aliyuncs.com/uploads/templates/7.png',
        createAt: new Date(),
        updateAt: new Date()
    },
    {
        name: '监控视频',
        size: '比例16:9↵↵1920x1080px',
        description: '模板简单描述',
        isdeleted: 0,
        priority: 1, 
        level: 1,
        thumbnail: 'https://img.alicdn.com/tfs/TB19_rvq7P2gK0jSZPxXXacQpXa-640-357.png',
        snapshot: 'http://img.alicdn.com/tfs/TB1rqF7qqL7gK0jSZFBXXXZZpXa-1600-900.gif',
        createAt: new Date(),
        updateAt: new Date()
    },
    {
        name: '监控视频',
        size: '比例16:9↵↵1920x1080px',
        description: '模板简单描述',
        isdeleted: 0,
        priority: 1, 
        level: 1,
        thumbnail: 'https://datav.oss-cn-hangzhou.aliyuncs.com/uploads/images/f853293a03c33ed15f15291b254ee47b.png',
        snapshot: 'https://img.alicdn.com/tfs/TB1zf8TelGE3KVjSZFhXXckaFXa-1600-900.gif',
        createAt: new Date(),
        updateAt: new Date()
    },
    {
        name: '监控视频',
        size: '比例16:9↵↵1920x1080px',
        description: '模板简单描述',
        isdeleted: 0,
        priority: 1, 
        level: 1,
        thumbnail: 'https://datav.oss-cn-hangzhou.aliyuncs.com/uploads/images/d2fe31ebb0b23f9c5952f4e55ca90c1d.png',
        snapshot: 'https://img.alicdn.com/tfs/TB1zn9TXFP7gK0jSZFjXXc5aXXa-1600-900.gif',
        createAt: new Date(),
        updateAt: new Date()
    },
    {
        name: '监控视频',
        size: '比例16:9↵↵1920x1080px',
        description: '模板简单描述',
        isdeleted: 0,
        priority: 1, 
        level: 1,
        thumbnail: 'https://datav.oss-cn-hangzhou.aliyuncs.com/uploads/images/1084d7bb3280a49a2b0c7be914925cd9.png',
        snapshot: 'https://img.alicdn.com/tfs/TB1H7rpaqL7gK0jSZFBXXXZZpXa-1600-900.gif',
        createAt: new Date(),
        updateAt: new Date()
    },
    {
        name: '监控视频',
        size: '比例16:9↵↵1920x1080px',
        description: '模板简单描述',
        isdeleted: 0,
        priority: 1, 
        level: 1,
        thumbnail: 'https://datav.oss-cn-hangzhou.aliyuncs.com/uploads/images/f853293a03c33ed15f15291b254ee47b.png',
        snapshot: 'https://img.alicdn.com/tfs/TB1zf8TelGE3KVjSZFhXXckaFXa-1600-900.gif',
        createAt: new Date(),
        updateAt: new Date()
    },
    {
        name: '监控视频',
        size: '比例16:9↵↵1920x1080px',
        description: '模板简单描述',
        isdeleted: 0,
        priority: 1, 
        level: 1,
        thumbnail: 'https://datav.oss-cn-hangzhou.aliyuncs.com/uploads/images/d2fe31ebb0b23f9c5952f4e55ca90c1d.png',
        snapshot: 'https://img.alicdn.com/tfs/TB1zn9TXFP7gK0jSZFjXXc5aXXa-1600-900.gif',
        createAt: new Date(),
        updateAt: new Date()
    },
    {
        name: '监控视频',
        size: '比例16:9↵↵1920x1080px',
        description: '模板简单描述',
        isdeleted: 0,
        priority: 1, 
        level: 1,
        thumbnail: 'https://datav.oss-cn-hangzhou.aliyuncs.com/uploads/images/1084d7bb3280a49a2b0c7be914925cd9.png',
        snapshot: 'https://img.alicdn.com/tfs/TB1H7rpaqL7gK0jSZFBXXXZZpXa-1600-900.gif',
        createAt: new Date(),
        updateAt: new Date()
    },
    {
        name: '监控视频',
        size: '比例16:9↵↵1920x1080px',
        description: '模板简单描述',
        isdeleted: 0,
        priority: 1, 
        level: 1,
        thumbnail: 'https://datav.oss-cn-hangzhou.aliyuncs.com/uploads/images/f853293a03c33ed15f15291b254ee47b.png',
        snapshot: 'https://img.alicdn.com/tfs/TB1zf8TelGE3KVjSZFhXXckaFXa-1600-900.gif',
        createAt: new Date(),
        updateAt: new Date()
    },
    {
        name: '监控视频',
        size: '比例16:9↵↵1920x1080px',
        description: '模板简单描述',
        isdeleted: 0,
        priority: 1, 
        level: 1,
        thumbnail: 'https://datav.oss-cn-hangzhou.aliyuncs.com/uploads/images/d2fe31ebb0b23f9c5952f4e55ca90c1d.png',
        snapshot: 'https://img.alicdn.com/tfs/TB1zn9TXFP7gK0jSZFjXXc5aXXa-1600-900.gif',
        createAt: new Date(),
        updateAt: new Date()
    },
    {
        name: '监控视频',
        size: '比例16:9↵↵1920x1080px',
        description: '模板简单描述',
        isdeleted: 0,
        priority: 1, 
        level: 1,
        thumbnail: 'https://datav.oss-cn-hangzhou.aliyuncs.com/uploads/images/1084d7bb3280a49a2b0c7be914925cd9.png',
        snapshot: 'https://img.alicdn.com/tfs/TB1H7rpaqL7gK0jSZFBXXXZZpXa-1600-900.gif',
        createAt: new Date(),
        updateAt: new Date()
    },
    {
        name: '监控视频',
        size: '比例16:9↵↵1920x1080px',
        description: '模板简单描述',
        isdeleted: 0,
        priority: 1, 
        level: 1,
        thumbnail: 'https://datav.oss-cn-hangzhou.aliyuncs.com/uploads/images/f853293a03c33ed15f15291b254ee47b.png',
        snapshot: 'https://img.alicdn.com/tfs/TB1zf8TelGE3KVjSZFhXXckaFXa-1600-900.gif',
        createAt: new Date(),
        updateAt: new Date()
    },
    {
        name: '监控视频',
        size: '比例16:9↵↵1920x1080px',
        description: '模板简单描述',
        isdeleted: 0,
        priority: 1, 
        level: 1,
        thumbnail: 'https://datav.oss-cn-hangzhou.aliyuncs.com/uploads/images/d2fe31ebb0b23f9c5952f4e55ca90c1d.png',
        snapshot: 'https://img.alicdn.com/tfs/TB1zn9TXFP7gK0jSZFjXXc5aXXa-1600-900.gif',
        createAt: new Date(),
        updateAt: new Date()
    },
    {
        name: '监控视频',
        size: '比例16:9↵↵1920x1080px',
        description: '模板简单描述',
        isdeleted: 0,
        priority: 1, 
        level: 1,
        thumbnail: 'https://datav.oss-cn-hangzhou.aliyuncs.com/uploads/images/1084d7bb3280a49a2b0c7be914925cd9.png',
        snapshot: 'https://img.alicdn.com/tfs/TB1H7rpaqL7gK0jSZFBXXXZZpXa-1600-900.gif',
        createAt: new Date(),
        updateAt: new Date()
    }
];